// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1GTcOF8cKNfdsHFZ55e5Jw3n4dsODI8',
    appId: '1:226320028391:web:4ba1b8929fd7de058e8842',
    messagingSenderId: '226320028391',
    projectId: 'projectlogin-anggaa',
    authDomain: 'projectlogin-anggaa.firebaseapp.com',
    databaseURL: 'https://projectlogin-anggaa-default-rtdb.firebaseio.com',
    storageBucket: 'projectlogin-anggaa.appspot.com',
    measurementId: 'G-98BBL13QTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqptJUCmivWsBCsbj7QoMNQcs8TUW742g',
    appId: '1:226320028391:android:871088958d81e29e8e8842',
    messagingSenderId: '226320028391',
    projectId: 'projectlogin-anggaa',
    databaseURL: 'https://projectlogin-anggaa-default-rtdb.firebaseio.com',
    storageBucket: 'projectlogin-anggaa.appspot.com',
  );
}
